### ISSUE TITLE
Fix a rare occurence of not being able to login after server stops sending stuff on certain config file

### ISSUE THREAD

**Issue by fiki574** [fiki574/rAPB#13]
So yea, every now and then, first time I want to login it goes to "ANS_CONFIG_FILE" packets and just hangs there. Closing the server(s) still leaves the client with that loading circle, thus having to completely shutdown APB and restart.

**Comment by dretax** [comment]
Probably needs packet confirmation?

**Comment by fiki574** [comment]
What?! Packet is fine, it just stops for unknown reason 1 in 5 times I'm logging in for first time, so no packet confirmation of any kind...

**Comment by fiki574** [comment]
Seems like it stopped occuring in last few days, closing this for now until further occurence (if any).
